image: python:3.11-slim

stages:
  - lint
  - build

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

🐶 ruff:
  stage: lint
  script: poetry run ruff resume

🍰 mypy:
  stage: lint
  script: poetry run mypy resume

🚀 build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/update_pipelines"
  needs:
    - 🐶 ruff
    - 🍰 mypy
  script:
    - apt-get update
    - apt-get install -y git xvfb libfontconfig wkhtmltopdf
    - poetry run python resume/main.py
    - git config --local user.email "ci@gitlab.com"
    - git config --local user.name "gitlab-ci"
    - git add resume.pdf --force
    - git commit -m "Generate resume pdf from GitLab CI"
    - git push https://${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git HEAD:$CI_COMMIT_REF_NAME
  